In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [3]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 109 ms
Wall time: 131 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 1.69 s
Wall time: 2.48 s


In [7]:
# Generate some random data
data = np.random.randn(2,3)
data

array([[-1.04798506,  1.70267797, -1.57161746],
       [ 1.01519479, -1.64647548, -0.56250242]])

In [8]:
data+data

array([[-2.09597011,  3.40535593, -3.14323492],
       [ 2.03038959, -3.29295096, -1.12500485]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data.size

6

In [12]:
len(data)

2

In [13]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print("arr1 shape dimention and size")
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)
print()
print("arr2 shape dimention and size")
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

arr1 shape dimention and size
(5,)
1
5
float64

arr2 shape dimention and size
(2, 4)
2
8
int64


In [16]:
# zeros and ones create arrays of 0s and 1s 
print(np.zeros(10))
print()
print(np.zeros((3,6)))
print()
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [17]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
a = np.arange(6).reshape(3,2)

In [19]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [21]:
b=np.arange(16).reshape(4,4)

In [22]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.zeros_like(b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
c = np.arange(25, dtype = float).reshape(5,5)
c

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [25]:
np.zeros_like(c)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
a1 = ([1,2,3],[4,5,6])
np.empty_like(a1)

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [25896041459482716, 19140779460001857,      416619429985]])

In [27]:
a1

([1, 2, 3], [4, 5, 6])

In [28]:
np.zeros_like(a1)

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
a2 = np.arange(16).reshape(4,4)
np.empty_like(a2)

array([[25895968444448860, 23925768161198147, 32370111954616435,
        25896041459482716],
       [34058953225207854, 30962724186357876, 31244212048494684,
        28429436511125606],
       [28710881422737503, 32651561162571873, 32370073300107356,
        34058961815535732],
       [30399782823591982, 12666807751278697, 32088649863463018,
             463862825070]])

In [30]:
b1 = np.empty_like([3,2], dtype = int)
b2 = np.empty_like([2,2], dtype = float)
print(b1)
print(b2)
print(b1.dtype)
print(b2.dtype)

[616844624499122135 918064193896623400]
[0. 0.]
int64
float64


In [31]:
b1 = np.empty((3,2), dtype = int)
b2 = np.empty((2,2), dtype = float)
print(b1)
print(b2)
print(b1.dtype)
print(b2.dtype)

[[1 2]
 [3 4]
 [5 6]]
[[6.  7.5]
 [8.  1. ]]
int64
float64


In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [37]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [38]:
#use of dype with eye function
print(np.eye(2,dtype=int))
print()
print(np.eye(5,dtype=float))

[[1 0]
 [0 1]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
x = np.arange(4)
x = x.reshape(2,2)
print(x)
print('\n')
print(np.ones_like(x))
print('\n')
y = np.arange(6).reshape(2,3)
print(np.ones_like(y))

[[0 1]
 [2 3]]


[[1 1]
 [1 1]]


[[1 1 1]
 [1 1 1]]


In [42]:
# Create an array with random values and same shape as arr
print("Array with random values:")
arr = np.random.rand(2, 3, 4)
print(arr)
arr_ones = np.ones_like(arr, dtype=int)
print("\nSame shape as above array, but with a different data type:")
print(arr_ones)
print(arr.dtype)
print(arr_ones.dtype)

Array with random values:
[[[0.08608265 0.84372584 0.05690291 0.6899044 ]
  [0.45573406 0.33878382 0.74490377 0.5306517 ]
  [0.42772961 0.74581909 0.80724514 0.43834081]]

 [[0.72935738 0.63919518 0.91796435 0.57387404]
  [0.62668645 0.54454012 0.60552095 0.4229343 ]
  [0.71458487 0.95386178 0.3081823  0.81261683]]]

Same shape as above array, but with a different data type:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
float64
int64


In [43]:
np.full(3,12)

array([12, 12, 12])

In [44]:
np.full([2,2],30)

array([[30, 30],
       [30, 30]])

In [45]:
np.full([3,4],55,dtype=float)

array([[55., 55., 55., 55.],
       [55., 55., 55., 55.],
       [55., 55., 55., 55.]])

In [46]:
a = np.arange(5)
print(np.full_like(a,3))
print(np.full_like(a,1.2))
b = a.astype(float)
print(np.full_like(b,1.2))
print(np.full_like(a,np.nan, dtype=np.double))

[3 3 3 3 3]
[1 1 1 1 1]
[1.2 1.2 1.2 1.2 1.2]
[nan nan nan nan nan]


In [47]:
a.dtype

dtype('int64')

# Data type

In [48]:
arr = np.array(range(127), dtype=np.int8)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126], dtype=int8)

In [49]:
arr = np.array(range(250), dtype=np.int32)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [50]:
arr = np.array(range(257), dtype=np.uint8)
arr

OverflowError: Python integer 256 out of bounds for uint8

In [51]:
arr = np.array(range(150), dtype=np.int_)
print(arr)
arr.dtype

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


dtype('int64')

# Array

In [52]:
# Create two dimensional array
x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3,4)) # two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # three dimensional array

In [53]:
x1

array([1, 6, 0, 3, 4, 1], dtype=int32)

In [54]:
x2

array([[4, 9, 8, 2],
       [6, 8, 4, 0],
       [0, 4, 8, 3]], dtype=int32)

In [55]:
x3

array([[[0, 4, 0, 0, 0],
        [0, 2, 3, 1, 9],
        [2, 9, 1, 4, 1],
        [7, 4, 3, 1, 2]],

       [[2, 1, 1, 5, 3],
        [6, 3, 1, 6, 2],
        [4, 3, 9, 9, 7],
        [3, 3, 7, 7, 8]],

       [[0, 0, 5, 7, 5],
        [9, 0, 9, 7, 3],
        [6, 0, 2, 7, 2],
        [0, 1, 2, 3, 4]]], dtype=int32)

In [56]:
# itemsize, which lists the size (in bytes) of each array element,
# nbytes, which lists the total size (in bytes) of the array
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
x3 itemsize: 4 bytes
x3 nbytes: 240 bytes


In [57]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [58]:
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [59]:
arr+10


array([[11., 12., 13.],
       [14., 15., 16.]])

In [60]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [61]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [64]:
10/arr

array([[10.        ,  5.        ,  3.33333333],
       [ 2.5       ,  2.        ,  1.66666667]])

In [65]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [66]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [67]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [68]:
x = np.arange(4)

In [69]:
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division  
print("-x = ", -x)
print("x  2 = ",x ,2)
print("x % 2 = ",x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x  2 =  [0 1 2 3] 2
x % 2 =  [0 1 0 1]


In [70]:
# Arithmetic functions
print("x =", x)
print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.negative(x))
print(np.power(x,3))
print(np.mod(x,2))

x = [0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[ 0  1  8 27]
[0 1 0 1]


In [71]:
l = np.random.random(100)

In [72]:
l 

array([0.01281651, 0.05385014, 0.45260378, 0.79785433, 0.89296154,
       0.41762198, 0.45473659, 0.69780421, 0.88627207, 0.36316466,
       0.8270037 , 0.24575537, 0.97600583, 0.16067558, 0.50634247,
       0.15138056, 0.98358823, 0.06635272, 0.8858321 , 0.09521887,
       0.72205794, 0.22922373, 0.89592391, 0.88264052, 0.44498709,
       0.02061739, 0.83823907, 0.32497441, 0.92342623, 0.89024338,
       0.12463493, 0.70481916, 0.05120537, 0.08368293, 0.29030227,
       0.86898146, 0.07269282, 0.18165426, 0.01044171, 0.27776724,
       0.87548591, 0.73974908, 0.46194788, 0.87983166, 0.62513051,
       0.22451284, 0.97105421, 0.45462388, 0.79871223, 0.11226624,
       0.46131108, 0.09704723, 0.19283455, 0.07231941, 0.03887776,
       0.43520494, 0.38282518, 0.56552387, 0.1984607 , 0.6638223 ,
       0.25287881, 0.94261795, 0.62729034, 0.32486681, 0.67288023,
       0.24768626, 0.18236049, 0.37318314, 0.38460338, 0.17915273,
       0.12422542, 0.86255513, 0.54371984, 0.95324259, 0.23644

In [73]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

247 ms ± 62.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.15 ms ± 23.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [74]:
a = np.random.randint(30, size=(5,6))

In [75]:
np.min(a)

np.int32(0)

In [76]:
np.max(a)

np.int32(29)

In [77]:
np.mean(a)

np.float64(18.433333333333334)

In [78]:
a.min(axis=0)

array([ 0,  6,  4, 16,  3, 13], dtype=int32)

In [79]:
a.std()

np.float64(7.990341391677552)

In [80]:
np.std(a)

np.float64(7.990341391677552)

In [81]:
a.var()

np.float64(63.845555555555556)

In [82]:
np.median(a)

np.float64(18.5)

In [83]:
data = pd.read_csv("president_heights.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'president_heights.csv'

In [ ]:
data

In [ ]:
data.info()

In [84]:
data.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [85]:
%timeit data["height(cm)"].min()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
%timeit np.array(data['height(cm)']).min()

In [ ]:
heights =  np.array(data['height(cm)'])

In [ ]:
print("Mean height: ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height: ", heights.min())
print("Maximum height: ", heights.max())

# Comparison operator

In [ ]:
x = np.array([1,2,3,4,5])

In [ ]:
x>3

In [ ]:
x<3

In [ ]:
x>=3

In [ ]:
x<=3

In [ ]:
np.equal(x,3)

In [ ]:
np.not_equal(x,3)

In [ ]:
np.less(x,3)

In [ ]:
np.less_equal(x,3)

In [ ]:
rng = np.random.randint(10, size=(3,4))
rng

In [ ]:
np.less(rng,6)

In [ ]:
x=rng.copy()

In [ ]:
x

In [ ]:
np.count_nonzero(x<6)

In [ ]:
# how many values less than 6
print(np.sum(x<6, axis=0))
print(np.sum(x<6,axis=1))

In [ ]:
np.any(x>6)

In [ ]:
np.any(x<0)

In [ ]:
np.all(x<10)

In [ ]:
np.all(x==6)

In [ ]:
x1

In [ ]:
x1[0]

In [ ]:
x1[4]

In [ ]:
x1[-1]

In [ ]:
x1[-2]

In [ ]:
x2

In [ ]:
x2[0,0]

# Random number

In [ ]:
n = np.random.randint(50)
print(n)

In [ ]:
n = np.random.randint(50,size=10)
print(n)


In [ ]:
#Generate a random integer from 1 to 10
n = np.random.randint(1,10)
print(n)