In [1]:
import numpy as np

In [2]:
a = 2

In [3]:
print(type(a))

<class 'int'>


In [4]:
a = np.array(a)

In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a.ndim

0

In [8]:
a = [1, 2, 3]

In [9]:
print(type(a))

<class 'list'>


In [10]:
a = np.array(a)
print(type(a))

<class 'numpy.ndarray'>


In [11]:
a.ndim

1

In [12]:
a = [[1, 2, 3]]

In [13]:
a = np.array(a)
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(a.ndim)

2


In [16]:
a = [[[1, 2, 3]]]
a = np.array(a)
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
3


In [17]:
a = [[1,2,3,4],[5,6,7,8],[10,11,12,13]]

In [18]:
print(a)
print(type(a))

[[1, 2, 3, 4], [5, 6, 7, 8], [10, 11, 12, 13]]
<class 'list'>


In [19]:
a = np.array(a)

In [20]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [21]:
a.ndim

2

In [22]:
a.shape

(3, 4)

In [3]:
a = [[1,2,3],[4,5,6]]
print(type(a))
a = np.array(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a)


<class 'list'>
<class 'numpy.ndarray'>
2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [5]:
a = [[1,2,3,4],
     [4,5,6,10],
     [1,23,2,3],
     [4,45,5,6]]
print(type(a))
a = np.array(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a)

<class 'list'>
<class 'numpy.ndarray'>
2
(4, 4)
[[ 1  2  3  4]
 [ 4  5  6 10]
 [ 1 23  2  3]
 [ 4 45  5  6]]


In [13]:
a = [[[1,2,3],
      [4,5,6]],
     [[10,11,12],
     [13,14,15]],
     [[123,124,125],
     [126,127,128]]]
print(type(a))
a = np.array(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a)     

<class 'list'>
<class 'numpy.ndarray'>
3
(3, 2, 3)
[[[  1   2   3]
  [  4   5   6]]

 [[ 10  11  12]
  [ 13  14  15]]

 [[123 124 125]
  [126 127 128]]]


In [14]:
a = [[1279,5623,34323]]

In [16]:
x = np.array(a,ndmin=5)

In [17]:
print(x)

[[[[[ 1279  5623 34323]]]]]


In [18]:
a = [1,2,3,4,5.5]
a = np.array(a)
print(a)

[1.  2.  3.  4.  5.5]


In [19]:
a = [1,2,3,4,5.5,2+100j]
a = np.array(a)
print(a)

[1.   +0.j 2.   +0.j 3.   +0.j 4.   +0.j 5.5  +0.j 2. +100.j]


In [20]:
a = [True,1]
a = np.array(a)
a

array([1, 1])

In [21]:
a = ['1',2,3,4,5.5,2+100j]
a = np.array(a)
print(a)

['1' '2' '3' '4' '5.5' '(2+100j)']


In [22]:
import numpy as np
a = np.array([[1,2,3]])
print(a)
a.shape

[[1 2 3]]


(1, 3)

In [23]:
b= a[0,1]
print(b)

2


In [24]:
b=a
print(b)

[[1 2 3]]


In [25]:
#creating an array with zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones((4,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.full((3,3),11,dtype=int)

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [32]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.diag([2,4,5])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])