In [1]:
import numpy as np
import pandas as pd

## Data Types

In [18]:
arr = np.array(range(127), dtype=np.int8)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126], dtype=int8)

In [4]:
arr = np.array(range(150), dtype=np.uint8)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149], dtype=uint8)

In [5]:
arr = np.array(range(150), dtype=np.int_)
print(arr)
arr.dtype

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


dtype('int32')

In [6]:
arr = np.array(range(150))
print(arr)
arr.dtype

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


dtype('int32')

In [7]:
arr = np.array(range(150), dtype=int)
print(arr)
arr.dtype

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


dtype('int32')

### You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:

#### In this example, integers is casting to floating point.

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [9]:
float_arr = arr.astype(float)
# is similar to float_arr = arr.astype(np.float64)

In [10]:
float_arr

array([1., 2., 3., 4., 5.])

In [11]:
float_arr.dtype

dtype('float64')

#### If I cast some floating-point numbers to be of integer dtype, the decimal part will be truncated

In [12]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [13]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [14]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

#### If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

In [15]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [16]:
numeric_string.dtype

dtype('S4')

In [17]:
numeric_string = numeric_string.astype(float)

In [18]:
numeric_string

array([ 1.25, -9.6 , 42.  ])

In [19]:
numeric_string * 2

array([  2.5, -19.2,  84. ])

In [20]:
numeric_string + 2

array([ 3.25, -7.6 , 44.  ])

## Basics of Numpy Array

In [21]:
#Attribute of arrays
#Indexing of arrays
#Slicing of arrays
#Reshaping of arrays
#Joining and splitting of arrays

### Numpy Array Attribute

In [5]:
# Attributes of arrays Determining the size, shape, memory consumption, and data types of arrays

In [6]:
# Create two dimensional array
x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3,4)) # two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # three dimensional array

In [7]:
x1

array([8, 4, 9, 0, 9, 6])

In [8]:
x2

array([[9, 6, 4, 7],
       [9, 3, 9, 5],
       [8, 9, 8, 4]])

In [9]:
x3

array([[[3, 8, 6, 7, 9],
        [0, 9, 8, 0, 9],
        [2, 4, 1, 7, 2],
        [5, 2, 0, 7, 1]],

       [[3, 2, 7, 7, 1],
        [1, 7, 7, 0, 7],
        [5, 4, 0, 8, 4],
        [9, 6, 0, 5, 0]],

       [[3, 9, 4, 6, 5],
        [5, 6, 7, 7, 9],
        [1, 9, 6, 9, 0],
        [0, 9, 3, 6, 1]]])

In [24]:
# itemsize, which lists the size (in bytes) of each array element,
# nbytes, which lists the total size (in bytes) of the array
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
x3 itemsize: 4 bytes
x3 nbytes: 240 bytes


## Arithmetic with NumPy Arrays

#### Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [114]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [115]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [116]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [117]:
arr + 10

array([[11., 12., 13.],
       [14., 15., 16.]])

In [118]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [119]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [120]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [121]:
10 + arr

array([[11., 12., 13.],
       [14., 15., 16.]])

In [122]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [123]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [124]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [126]:
x = np.arange(4)

In [128]:
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division  
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)


x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [139]:
# Arithmetic functions
print("x =", x)
print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.negative(x))
print(np.power(x,3))
print(np.mod(x,2))

x = [0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[ 0  1  8 27]
[0 1 0 1]


In [140]:
# Absolute value
x = np.array([-2,-1,0,1,2])

In [141]:
x

array([-2, -1,  0,  1,  2])

In [142]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [143]:
np.abs(x)

array([2, 1, 0, 1, 2])

## Aggregation

In [144]:
l = np.random.random(100)

In [145]:
l

array([0.69977801, 0.74669119, 0.67971432, 0.4217637 , 0.2359924 ,
       0.30424978, 0.46581691, 0.98993391, 0.68508173, 0.31322265,
       0.56806683, 0.44852819, 0.71092299, 0.23757837, 0.67551976,
       0.89999428, 0.74377384, 0.66783413, 0.27605099, 0.03206564,
       0.37170297, 0.61485658, 0.43516201, 0.98159936, 0.29174119,
       0.68191019, 0.9667471 , 0.51491871, 0.45877369, 0.12368933,
       0.16546631, 0.37433412, 0.21584117, 0.5158585 , 0.86010302,
       0.61890396, 0.25396117, 0.87441403, 0.58761302, 0.56524773,
       0.3271075 , 0.09776656, 0.31193395, 0.01778105, 0.53042218,
       0.60807844, 0.73411791, 0.3988959 , 0.59105258, 0.44781368,
       0.08786763, 0.8823786 , 0.09178846, 0.1922565 , 0.05549435,
       0.07621576, 0.90426554, 0.1462244 , 0.08739954, 0.87211515,
       0.36317645, 0.1331445 , 0.29285887, 0.33087919, 0.18080986,
       0.89925863, 0.1184672 , 0.94832515, 0.51592878, 0.78153974,
       0.63113019, 0.14759529, 0.54989286, 0.92676261, 0.76726

In [148]:
print(sum(l))
print(np.sum(l))

49.03417441502944
49.034174415029455


#### NumPy’s version of the operation is computed much more quickly:


In [152]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

119 ms ± 3.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.52 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [153]:
# minimum value
a = np.random.randint(30, size=(5,6))

In [154]:
a

array([[26, 12,  0,  9,  1, 20],
       [ 6, 27, 18,  6, 19, 22],
       [ 8, 13,  9,  5, 13, 18],
       [ 2, 12, 10, 22,  1, 14],
       [ 3, 26,  1, 19, 14, 21]])

In [156]:
np.min(a)

0

In [157]:
np.max(a)

27

In [158]:
np.mean(a)

12.566666666666666

In [159]:
a.min()

0

In [160]:
a.min(axis=0)

array([ 2, 12,  0,  5,  1, 14])

In [161]:
a.max(axis=1)

array([26, 27, 18, 22, 26])

In [162]:
a.std()

8.122739001647714

In [163]:
np.std(a)

8.122739001647714

In [166]:
a.mean(axis=0)

array([ 9. , 18. ,  7.6, 12.2,  9.6, 19. ])

In [167]:
a.var()

65.97888888888889

In [168]:
a.prod()

0

In [170]:
np.median(a)

12.5

### Example: What is the average heighto of US President?

In [177]:
data = pd.read_csv("president_heights.csv")

In [178]:
data

,order,name,height(cm)
0,1,George Washington,189
1,2,John Adams,170
2,3,Thomas Jefferson,189
3,4,James Madison,163
4,5,James Monroe,183
5,6,John Quincy Adams,171
6,7,Andrew Jackson,185
7,8,Martin Van Buren,168
8,9,William Henry Harrison,173
9,10,John Tyler,183


In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   order       44 non-null     int64 
 1   name        44 non-null     object
 2   height(cm)  44 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.2+ KB


In [180]:
data.columns

Index(['order', 'name', 'height(cm)'], dtype='object')

In [185]:
%timeit data["height(cm)"].min()

36.8 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [186]:
%timeit np.array(data['height(cm)']).min()

15.7 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [191]:
heights =  np.array(data['height(cm)'])

In [192]:
heights

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185, 191, 182], dtype=int64)

In [195]:
print("Mean height: ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height: ", heights.min())
print("Maximum height: ", heights.max())

Mean height:  180.04545454545453
Standard deviation: 6.983599441335736
Minimum height:  163
Maximum height:  193


In [197]:
print("25th percentile: ", np.percentile(heights, 25))
print("Median: ", np.median(heights))
print("75th percentile: ", np.percentile(heights, 75))

25th percentile:  174.75
Median:  182.0
75th percentile:  183.5


### Comparision Operator

In [198]:
x = np.array([1,2,3,4,5])

In [199]:
x

array([1, 2, 3, 4, 5])

In [200]:
x<3

array([ True,  True, False, False, False])

In [201]:
x>3

array([False, False, False,  True,  True])

In [202]:
x<=3

array([ True,  True,  True, False, False])

In [203]:
x>=3

array([False, False,  True,  True,  True])

In [204]:
x!=3

array([ True,  True, False,  True,  True])

In [205]:
x==3

array([False, False,  True, False, False])

In [206]:
(2*x) ==(x**2)

array([False,  True, False, False, False])

In [207]:
np.equal(x,3)

array([False, False,  True, False, False])

In [208]:
np.not_equal(x,3)

array([ True,  True, False,  True,  True])

In [209]:
np.less(x,3)

array([ True,  True, False, False, False])

In [210]:
np.less_equal(x,3)

array([ True,  True,  True, False, False])

In [211]:
np.greater(x,3)

array([False, False, False,  True,  True])

In [212]:
np.greater_equal(x,3)

array([False, False,  True,  True,  True])

In [213]:
rng = np.random.randint(10, size=(3,4))
rng

array([[5, 1, 3, 3],
       [6, 7, 9, 3],
       [7, 8, 7, 8]])

In [214]:
np.less(rng,6)

array([[ True,  True,  True,  True],
       [False, False, False,  True],
       [False, False, False, False]])

### Working with Boolean Arrays

In [215]:
x = rng.copy() 

In [224]:
x

array([[5, 1, 3, 3],
       [6, 7, 9, 3],
       [7, 8, 7, 8]])

In [225]:
# how many values less than 6
np.count_nonzero(x<6)

5

In [226]:
# how many values less than 6
print(np.sum(x<6, axis=0))
print(np.sum(x<6,axis=1))

[1 1 1 2]
[4 1 0]


In [227]:
# are there any values greater than 8
np.any(x>8)

True

In [229]:
# are there any values less than 0
np.any(x<0)

False

In [230]:
# are all values less than 10 
np.all(x<10)

True

In [231]:
# are all values equal to 6
np.all(x==6)

False

In [233]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False, False])

### Basic Indexing and Slicing

#### NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [36]:
x1

array([3, 3, 7, 2, 6, 4])

In [37]:
x1[0]

3

In [38]:
x1[4]

6

In [39]:
x1[-1]

4

In [40]:
x1[-2]

6

In [41]:
x2

array([[0, 0, 8, 5],
       [1, 8, 4, 3],
       [9, 5, 2, 0]])

In [42]:
x2[0,0]

0

In [43]:
x2[0,3]

5

In [44]:
x2[2,3]

0

In [45]:
x2[2,-1]

0

In [46]:
# array modification -  assign value
x2[0,0] = 12

In [47]:
x2 

array([[12,  0,  8,  5],
       [ 1,  8,  4,  3],
       [ 9,  5,  2,  0]])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[5]

5

In [51]:
arr[5:8]

array([5, 6, 7])

In [52]:
arr[5:]

array([5, 6, 7, 8, 9])

In [53]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
# assing scalar value
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1] = 12345

In [60]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr1 = np.arange(10)

In [62]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr1_slice = arr1[5:8].copy()

In [64]:
arr1_slice[5:8] = 12

In [65]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x2

array([[12,  0,  8,  5],
       [ 1,  8,  4,  3],
       [ 9,  5,  2,  0]])

In [67]:
x2[:2,:3]

array([[12,  0,  8],
       [ 1,  8,  4]])

In [68]:
x2[:3,::2]

array([[12,  8],
       [ 1,  4],
       [ 9,  2]])

In [69]:
x2[::-1,::-1]

array([[ 0,  2,  5,  9],
       [ 3,  4,  8,  1],
       [ 5,  8,  0, 12]])

In [70]:
x2[:,0]

array([12,  1,  9])

In [71]:
x2[0,:]

array([12,  0,  8,  5])

### Reshaping of array

In [72]:
x = np.array([1,2,3])

In [73]:
# row vector via reshape
x.reshape(1,3)

array([[1, 2, 3]])

In [74]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [75]:
# column vector via reshape
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [76]:
# column vector via newaxis
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

##### All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We’ll take a look at those operations here.

##### Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines np.concatenate, np.vstack, and np.hstack.

In [108]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y]) # or np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [109]:
# concatenate more than two arrays at once
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [111]:
# two dimensional array
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
# concate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [117]:
# concte along the second axis
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [78]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])

In [81]:
np.concatenate([x,grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [82]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.vstack([grid,x])

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [92]:
np.hstack([x,grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [90]:
y = np.array([[99],
              [99]])

In [88]:
np.hstack([y,grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [89]:
np.hstack([grid,y])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

#### Splitting of arrays

##### The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points: 

In [96]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5]) #3 and 5 are indices
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [97]:
# Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit
# and np.vsplit are similar:

In [99]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
upper,lower = np.vsplit(grid,[1]) # 1 is indice
print(upper,'\n','\n',lower)

[[0 1 2 3]] 
 
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [107]:
upper,lower = np.vsplit(grid,[3])
print(upper,'\n','\n',lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 
 [[12 13 14 15]]


In [112]:
left, right = np.hsplit(grid,[2])
print(left,'\n ',' \n',right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
   
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
