# Random Numbers in Numpy

#### Random number - that can not be predicted logically

In [1]:
import numpy as np
import pandas as pd

### Generate a random integer

In [5]:
#Generate a random integer from 0 to 50
n = np.random.randint(50)
print(n)

39


In [9]:
#Generate a random integer from 1 to 10
n = np.random.randint(1,10)
print(n)

3


### Generate random array

In [11]:
# Generate a one dimension array containing 10 intergers from 0 to 100
n = np.random.randint(100, size=(10))
n

array([59, 61, 49, 46, 10, 69, 31, 57, 89, 90])

In [12]:
# Generate a two dimension array containing 4 rows and each row contain 6 random intergers from 0 to 100
n = np.random.randint(100, size=(4,5))
n

array([[ 1, 45, 39, 13, 90],
       [45, 36, 38, 24, 32],
       [40, 10, 35,  1, 30],
       [89, 64, 74, 18, 93]])

In [15]:
# Generate a one dimesional arrary containing 10 random integers
# rand function generate floating type random number between  0 and 1
n = np.random.rand(10)
n

array([0.15930596, 0.27199964, 0.44397398, 0.23677979, 0.68488962,
       0.48208477, 0.11991728, 0.53662858, 0.86775964, 0.27611464])

In [16]:
#Generate a two dimenstional array with 5 rows, each row containing 6 floating point random numbers between 0 and 1:
n = np.random.rand(5,6)
n

array([[0.80138838, 0.35153266, 0.10028104, 0.14774022, 0.7866915 ,
        0.64625862],
       [0.46424622, 0.39645047, 0.16244615, 0.58550813, 0.9244231 ,
        0.21607728],
       [0.5721695 , 0.09429432, 0.01716559, 0.54298551, 0.22390494,
        0.07027469],
       [0.91038802, 0.32398337, 0.7280762 , 0.0584132 , 0.6212542 ,
        0.36821583],
       [0.99014399, 0.26846195, 0.6387436 , 0.51822239, 0.87843982,
        0.80733988]])

### Generate random number from array

In [22]:
#The choice() method takes an array as a parameter and return random value from array.
n = np.random.choice([3,5,7,9])
n

9

In [24]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
n = np.random.choice([3,5,7,9], size=(3,5))
n

array([[9, 5, 9, 7, 3],
       [9, 3, 5, 3, 5],
       [9, 5, 3, 7, 5]])