In [1]:
import numpy as np
import pandas as pd

## Random Integers And Random Numbers

In [26]:
# np.random.randint(1, 7) generate a random integer from 1 to 6
# np.random.rand() generate a random number between 0 and 1

## Random Int

In [3]:
# Generate a radom integer from 0 to 100
x = np.random.randint(100)
x

71

In [9]:
# generate 5 random numbers
for i in range(5):
    x = np.random.randint(100)
    print(x)

70
42
74
74
87


In [10]:
# generate 1D array of 5 random integers between 0 and 9
integer_array = np.random.randint(0, 10, 5)

print("1D Random Integer Array:\n",integer_array)

1D Random Integer Array:
 [7 8 8 5 2]


In [18]:
a = np.random.randint(3, size=10)
a

array([2, 0, 1, 0, 0, 2, 1, 2, 0, 2])

In [11]:
# Generate random integer from 0 to 9
# 0 - a lower bound(inclusive), 10 - an upper bound (exclusive)
r = np.random.randint(0,10)
r

5

In [13]:
# generate 2D array of shape (3, 4) with random integers
result = np.random.randint(0, 10, (3,4))

print("\n2D Random Integer Array:\n",result)


2D Random Integer Array:
 [[3 0 9 1]
 [6 5 8 9]
 [1 5 3 6]]


### Tossing A Coin 3 Times

#### np.random.randint(2) takes parameter 2 because it generates a random integer from [0, 1]. 0 represent tail, 1 represent head

In [27]:
# Tossing Coin 1st Time
print(np.random.randint(2))

# Tossing Coin 2st Time
print(np.random.randint(2))

# Tossing Coin 3rd Time
print(np.random.randint(2))

0
1
0


### Tossing Two Coins 3 Times

In [28]:
# Tossing 2-Coins 1st Time
print(np.random.randint(2, size = 2))

# Tossing 2-Coins 2nd Time
print(np.random.randint(2, size = 2))

# Tossing 2-Coins 3rd Time
print(np.random.randint(2, size = 2))

[0 0]
[0 1]
[0 1]


### Rolling A Dice Two Times

#### We have one dice and roll it two times  np.random.randint(1, 7) yields result from 1 to 6.

In [29]:
print(np.random.randint(1, 7))

print(np.random.randint(1, 7))

3
6


### Rolling Two Dice Three Times

In [30]:
print(np.random.randint(1, 7, size = 2))

print(np.random.randint(1, 7, size = 2))

print(np.random.randint(1, 7, size = 2))

[5 2]
[4 6]
[6 2]


## Random Float

In [5]:
# Generate a random float
# We can also generate a random floating-point number between 0 and 1. 

x = np.random.rand()
x

0.6345885878292529

In [12]:
# generate 1D array of 5 random numbers between 0 and 1
float_array = np.random.rand(5)

print("\n1D Random Float Array:\n",float_array)


1D Random Float Array:
 [0.77601755 0.71732228 0.62466552 0.72419442 0.06162005]


In [15]:
# generate 2D array of 10 random numbers between 0 and 1
float_array = np.random.rand(5,2)

print("\n2D Random Float Array:\n",float_array)


2D Random Float Array:
 [[0.13692517 0.15074863]
 [0.66068715 0.24501901]
 [0.86541343 0.35999055]
 [0.92404088 0.32408058]
 [0.28826952 0.53498219]]


In [22]:
# 3D Array     
array = np.random.rand(3, 2 ,2)
print("\n\n3D Array filled with random values : \n", array);



3D Array filled with random values : 
 [[[0.48601642 0.5153938 ]
  [0.20150118 0.21833972]]

 [[0.4131057  0.55480364]
  [0.28088078 0.46068496]]

 [[0.01829421 0.20542508]
  [0.93867572 0.79533326]]]


In [31]:
# generate a matrix of size 5-by-3 from number 1 to 8
print(np.random.randint(1, 9, size = (5, 3)))

[[8 4 5]
 [1 4 2]
 [6 5 4]
 [1 1 3]
 [3 7 2]]


In [25]:
np.random.seed(42)
random_numbers = np.random.random(size=4)
random_numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Choice

In [32]:
# create an array of integers from 1 to 5
array1 = np.array([1, 2, 3, 4, 5])

# choose a random number from array1
random_choice = np.random.choice(array1)

print(random_choice)

4


In [33]:
# Choose A Matrix Of Random Numbers From A List
print(np.random.choice([1,2,3,4,5,6], size = (2, 5)))

[[4 6 6 6 3]
 [4 4 1 3 5]]


### Shuffle The Elements Of The List

#### shuffle() changing the arrangement of the elements in-place such that the original array is changed.

#### permutation() The permutation() method returns a re-arranged array such that the original array is unchanged.

#### shuffle()

In [35]:
mylist = np.array(['USA', 'India', 'China', 'Dubai'])
np.random.shuffle(mylist)
print(mylist)

['Dubai' 'India' 'China' 'USA']


#### permutaion()

In [38]:
mylist = np.array(['USA', 'India', 'China', 'Dubai'])
print(np.random.permutation(mylist))
print(mylist)

['China' 'Dubai' 'India' 'USA']
['USA' 'India' 'China' 'Dubai']


### Example1:- Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [45]:
# Generating an array 'x' with numbers from 0 to 9 using np.arange()
x = np.arange(10)
print(x)
# Shuffling the elements of the array 'x' in-place using np.random.shuffle()
np.random.shuffle(x)

# Printing the shuffled array 'x'
print(x)

# Generating a permutation of numbers from 0 to 9 using np.random.permutation()
# and printing the result
print("Same result using permutation():")
print(x)
print(np.random.permutation(x))
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 2 1 9 7 6 3 5 4 8]
Same result using permutation():
[0 2 1 9 7 6 3 5 4 8]
[2 1 5 7 4 6 0 9 3 8]
[0 2 1 9 7 6 3 5 4 8]


### Example2 - Write a NumPy program to generate six random integers between 10 and 30.

In [46]:
# Generating a NumPy array 'x' of size 6 with random integers between 10 (inclusive) and 30 (exclusive) using np.random.randint()

x = np.random.randint(low=10, high=30, size=6)

# Printing the array 'x'
print(x) 

[29 22 18 12 16 15]


In [47]:
# Generating a NumPy array 'x' of size 6 with random integers between 10 (inclusive) and 30 (exclusive) using np.random.randint()

x = np.random.randint(10,30, size=6)

# Printing the array 'x'
print(x) 

[17 18 14 10 28 19]


In [48]:
# Generating a NumPy array 'x' of size 6 with random integers between 10 (inclusive) and 30 (exclusive) using np.random.randint()

x = np.random.randint(10,30,6)

# Printing the array 'x'
print(x) 

[21 24 18 29 26 26]


### Example3- Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [49]:
# Generating a 5x5 NumPy array 'x' filled with random floats between 0 and 1 using np.random.random()

x = np.random.random((5, 5))

# Printing the original array 'x'
print("Original Array:")
print(x)

# Calculating the minimum and maximum values in array 'x' using x.min() and x.max() functions
xmin, xmax = x.min(), x.max()

# Printing the minimum and maximum values of the array 'x'
print("Minimum and Maximum Values:")
print(xmin, xmax) 

Original Array:
[[0.25391541 0.24687606 0.69630427 0.71227059 0.14808693]
 [0.99774049 0.26678101 0.97661496 0.41103701 0.03305073]
 [0.34507125 0.63435134 0.68070545 0.53093458 0.44778316]
 [0.55289309 0.59269672 0.08085333 0.36965446 0.24215994]
 [0.80313976 0.47030063 0.98342314 0.39882444 0.81643187]]
Minimum and Maximum Values:
0.033050732900548385 0.9977404850489419


In [51]:
# same as above but different method
# Generating a 5x5 NumPy array 'x' filled with random floats between 0 and 1 using np.random.random()

x = np.random.rand(5, 5)

# Printing the original array 'x'
print("Original Array:")
print(x)

# Calculating the minimum and maximum values in array 'x' using x.min() and x.max() functions
xmin, xmax = x.min(), x.max()

# Printing the minimum and maximum values of the array 'x'
print("Minimum and Maximum Values:")
print(xmin, xmax) 

Original Array:
[[0.9962537  0.96541935 0.55829345 0.88263634 0.18870711]
 [0.27887135 0.70035783 0.84666114 0.85632429 0.40450813]
 [0.8877701  0.85092845 0.93563499 0.78534065 0.66898825]
 [0.58068662 0.37228277 0.94013344 0.97366384 0.28392097]
 [0.30536386 0.48561375 0.44842414 0.99445746 0.17592525]]
Minimum and Maximum Values:
0.17592525267734538 0.9962536997579243


### Example4 -Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [52]:
# Generating a 10x4 NumPy array 'x' filled with random floats between 0 and 1 using np.random.rand()
x = np.random.rand(10, 4)

# Printing the original array 'x'
print("Original array:")
print(x)

# Selecting the first 5 rows of the array 'x' and storing it in variable 'y' using array slicing
y = x[:5, :]

# Printing the first 5 rows of the original array 'x' stored in 'y'
print("First 5 rows of the above array:")
print(y) 

Original array:
[[0.01807536 0.49389372 0.17882271 0.36646878]
 [0.74417052 0.72093992 0.30806079 0.54254023]
 [0.50881408 0.63633262 0.25046182 0.58987085]
 [0.97889286 0.48674215 0.90609879 0.43439437]
 [0.35007841 0.64510336 0.66892406 0.86416757]
 [0.23018527 0.49919338 0.5720042  0.76855401]
 [0.04360377 0.99455051 0.46994451 0.27956034]
 [0.88349402 0.74771877 0.95307185 0.3307503 ]
 [0.55276497 0.57229247 0.98033158 0.07534626]
 [0.30569702 0.19091103 0.26847486 0.48527987]]
First 5 rows of the above array:
[[0.01807536 0.49389372 0.17882271 0.36646878]
 [0.74417052 0.72093992 0.30806079 0.54254023]
 [0.50881408 0.63633262 0.25046182 0.58987085]
 [0.97889286 0.48674215 0.90609879 0.43439437]
 [0.35007841 0.64510336 0.66892406 0.86416757]]


### Example5 - Write a NumPy program to create a random vector of size 10 and sort it.

In [53]:
# Generating a 1D array of 10 random numbers between 0 and 1 using np.random.random()
x = np.random.random(10)

# Printing the original array 'x'
print("Original array:")
print(x)

# Sorting the array 'x' in ascending order using x.sort()
x.sort()

# Printing the sorted array 'x'
print("Sorted array:")
print(x) 

Original array:
[0.37268687 0.39469147 0.84421314 0.93001683 0.07041613 0.20891872
 0.67114352 0.35864678 0.25416365 0.29529059]
Sorted array:
[0.07041613 0.20891872 0.25416365 0.29529059 0.35864678 0.37268687
 0.39469147 0.67114352 0.84421314 0.93001683]


In [57]:
# Generating a 1D array of 10 random numbers between 0 and 1 using np.random.random()
x = np.random.randint(10,30,10)

# Printing the original array 'x'
print("Original array:")
print(x)

# Sorting the array 'x' in ascending order using x.sort()
x.sort()

# Printing the sorted array 'x'
print("Sorted array:")
print(x) 
print(x[::-1])
print(np.argsort(x))

Original array:
[21 28 24 11 11 28 26 29 19 15]
Sorted array:
[11 11 15 19 21 24 26 28 28 29]
[29 28 28 26 24 21 19 15 11 11]
[0 1 2 3 4 5 6 7 8 9]


### Example6 - Write a NumPy program to check two random arrays are equal or not.

In [59]:
# Generating the first array 'x' with 6 random integers (0 or 1) using np.random.randint()
x = np.random.randint(0, 2, 6)

# Printing the first generated array 'x'
print("First array:")
print(x)

# Generating the second array 'y' with 6 random integers (0 or 1) using np.random.randint()
y = np.random.randint(0, 2, 6)

# Printing the second generated array 'y'
print("Second array:")
print(y)

# Checking if the two arrays 'x' and 'y' are equal using np.allclose()
# This function returns True if the two arrays are element-wise equal within a tolerance
array_equal = np.allclose(x, y)

# Printing whether the two arrays are equal or not
print("Test above two arrays are equal or not!")
print(array_equal)

First array:
[0 1 1 0 1 1]
Second array:
[1 0 0 0 1 1]
Test above two arrays are equal or not!
False


### Example7 - Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [60]:
# Generating an array 'x' with 15 random floats between 0 and 1 using np.random.random()
x = np.random.random(15)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Finding the index of the maximum value in the array using x.argmax()
# Replacing the maximum value with -1 using the index obtained from x.argmax()
x[x.argmax()] = -1

# Displaying the modified array where the maximum value has been replaced by -1
print("Maximum value replaced by -1:")
print(x) 

Original array:
[0.13274542 0.96953687 0.7145951  0.04106752 0.3988209  0.43352074
 0.74404264 0.25086053 0.18433367 0.08087297 0.42831447 0.6884999
 0.0581936  0.91521373 0.44235223]
Maximum value replaced by -1:
[ 0.13274542 -1.          0.7145951   0.04106752  0.3988209   0.43352074
  0.74404264  0.25086053  0.18433367  0.08087297  0.42831447  0.6884999
  0.0581936   0.91521373  0.44235223]


In [64]:
# Generating an array 'x' with 15 random floats between 0 and 1 using np.random.random()
x = np.random.randint(15, size=15)

# Displaying the original array 'x'
print("Original array:")
print(x)
print(np.argmax(x))

# Finding the index of the maximum value in the array using x.argmax()
# Replacing the maximum value with -1 using the index obtained from x.argmax()
x[np.argmax(x)] = -1

# Displaying the modified array where the maximum value has been replaced by -1
print("Maximum value replaced by -1:")
print(x) 

Original array:
[ 2  4  5  8 12 13 11  4 14  0 13 13 13  3  4]
8
Maximum value replaced by -1:
[ 2  4  5  8 12 13 11  4 -1  0 13 13 13  3  4]
