In [1]:
import numpy as np
import pandas as pd

### The performance difference, consider a NumPy array of one million integers, and the equivalent Python list:

In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [10]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [12]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [4]:
 %time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 50 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 1.58 s
Wall time: 1.57 s


### NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

## The NumPy ndarray: A Multidimensional Array Object

In [14]:
# Generate some random data
data = np.random.randn(2,3)
data

array([[-0.25224586, -0.73155624,  0.60084737],
       [ 0.87387964,  0.00404514, -1.36213534]])

#### One of the key features of NumPy is its N-dimensional array object, or ndarray,which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to thee quivalent operations between scalar elements.

In [30]:
# all the elements of array multiplied by 10
data*10

array([[16.23866791, 16.12953334,  9.43170426],
       [ 2.69167081,  5.54104689,  1.71026646]])

In [31]:
#Corresponding value added in two array
data+data

array([[3.24773358, 3.22590667, 1.88634085],
       [0.53833416, 1.10820938, 0.34205329]])

In [32]:
# shape of array
data.shape

(2, 3)

In [33]:
# data types of array
data.dtype

dtype('float64')

In [35]:
# no. of elements in array
data.size

6

In [36]:
len(data)

2

### Creating an array

In [38]:
# Use array function to create an array
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [40]:
#Nested sequence will be converted into a multidimentional array
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
print("arr1 shape dimention and size")
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)
print()
print("arr2 shape dimention and size")
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

arr1 shape dimention and size
(5,)
1
5
float64

arr2 shape dimention and size
(2, 4)
2
8
int32


In [49]:
# zeros and ones create arrays of 0s and 1s 
print(np.zeros(10))
print()
print(np.zeros((3,6)))
print()
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [54]:
"""It’s not safe to assume that np.empty will return an array of all 
zeros. In some cases, it may return uninitialized “garbage” values.
""" 
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
#arange is an array-valued version of the built-in Python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
"""The numpy.zeros_like() function takes an array_like object 
as input and returns an array of the same shape, size, 
and dtype with all elements set to zero.
    This function is useful when you want to create an array of
zeros with the same shape and type as another array without 
explicitly specifying the shape and data type. 
It can also be used to initialize a new array with the same shape 
as an existing array but with all elements set to zero."""

'The numpy.zeros_like() function takes an array_like object \nas input and returns an array of the same shape, size, \nand dtype with all elements set to zero.\n    This function is useful when you want to create an array of\nzeros with the same shape and type as another array without \nexplicitly specifying the shape and data type. \nIt can also be used to initialize a new array with the same shape \nas an existing array but with all elements set to zero.'

In [60]:
a = np.arange(4).reshape(2,2)

In [61]:
a

array([[0, 1],
       [2, 3]])

In [62]:
np.zeros_like(a)

array([[0, 0],
       [0, 0]])

In [64]:
b = np.arange(16).reshape(4,4)

In [65]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.zeros_like(b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
c = np.arange(25, dtype = float).reshape(5,5)
c

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [68]:
np.zeros_like(c)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
""" The numpy.empty_like() function is used to create a 
new array with the same shape and data type as a given array.
One common use case for numpy.empty_like() is when you want to 
create a new array with the same shape as an existing array, 
but with uninitialized values. This can be useful when you need 
to allocate memory for an array before filling it with data, 
as it can be faster than creating an array with initialized 
values.  """

' The numpy.empty_like() function is used to create a \nnew array with the same shape and data type as a given array.\nOne common use case for numpy.empty_like() is when you want to \ncreate a new array with the same shape as an existing array, \nbut with uninitialized values. This can be useful when you need \nto allocate memory for an array before filling it with data, \nas it can be faster than creating an array with initialized \nvalues.  '

In [2]:
a1 = ([1,2,3],[4,5,6])
np.empty_like(a1)

array([[-1580376032,         379, -1580376048],
       [        379,  -552401536,       32763]])

In [4]:
a1

([1, 2, 3], [4, 5, 6])

In [ ]:
a1 = np.array()

In [5]:
a2 = np.arange(16).reshape(4,4)
np.empty_like(a2)

array([[   0,    0,    0,    0],
       [   0,    0,    0,    0],
       [   0,    0, 1484,    0],
       [   0,    0,    0,    0]])

In [6]:
b1 = np.empty_like([3,2], dtype = int)
b2 = np.empty_like([2,2], dtype = float)
print(b1)
print(b2)
print(b1.dtype)
print(b2.dtype)

[-1998362383  1055193269]
[ 2.90133289e+263 -1.73150697e-244]
int32
float64


In [88]:
"""The eye() function is used to create a 2-D array with ones on
the diagonal and zeros elsewhere.
The eye() function is commonly used in linear algebra and 
matrix operations. It is useful for generating matrices to 
transform, rotate, or scale vectors. It can also be used in 
scientific computing for solving differential equations, 
optimization, and signal processing."""

'The eye() function is used to create a 2-D array with ones on\nthe diagonal and zeros elsewhere.\nThe eye() function is commonly used in linear algebra and \nmatrix operations. It is useful for generating matrices to \ntransform, rotate, or scale vectors. It can also be used in \nscientific computing for solving differential equations, \noptimization, and signal processing.'

In [89]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [99]:
#both are same
print(np.eye(3))
print("or")
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
or
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [94]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [95]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
#use of dype with eye function
print(np.eye(2,dtype=int))
print()
print(np.eye(5,dtype=float))

[[1 0]
 [0 1]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [109]:
""" An identity matrix is a square matrix in which all the 
elements of the main diagonal are equal to 1 and all other
elements are equal to 0. The identity() function return the 
identity array.
This function is useful in linear algebra, where the identity 
matrix plays an important role in representing the identity 
transformation in vector spaces. Identity matrices are also 
useful in testing matrix operations and algorithms, as they
have special properties that make them easy to work with."""

' An identity matrix is a square matrix in which all the \nelements of the main diagonal are equal to 1 and all other\nelements are equal to 0. The identity() function return the \nidentity array.\nThis function is useful in linear algebra, where the identity \nmatrix plays an important role in representing the identity \ntransformation in vector spaces. Identity matrices are also \nuseful in testing matrix operations and algorithms, as they\nhave special properties that make them easy to work with.'

In [113]:
np.identity(2) # #default data type is float

array([[1., 0.],
       [0., 1.]])

In [114]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [115]:
np.identity(2,3)

TypeError: Cannot interpret '3' as a data type

In [116]:
"""The numpy.ones_like() function is used to get an array of ones with the same shape and type 
as an existing array."""

'The numpy.ones_like() function is used to get an array of ones with the same shape and type \nas an existing array.'

In [126]:
x = np.arange(4)
x = x.reshape(2,2)
print(x)
print('\n')
print(np.ones_like(x))
print('\n')
y = np.arange(6).reshape(2,3)
print(np.ones_like(y))

[[0 1]
 [2 3]]


[[1 1]
 [1 1]]


[[1 1 1]
 [1 1 1]]


In [2]:
import numpy as np

In [3]:
# Create an array with random values and same shape as arr
print("Array with random values:")
arr = np.random.rand(2, 3, 4)
print(arr)
arr_ones = np.ones_like(arr, dtype=int)
print("\nSame shape as above array, but with a different data type:")
print(arr_ones)
print(arr.dtype)
print(arr_ones.dtype)

Array with random values:
[[[0.22383265 0.67975998 0.16038529 0.1382935 ]
  [0.73606658 0.33646185 0.99440301 0.56560963]
  [0.58776939 0.109846   0.62847127 0.59569997]]

 [[0.57478046 0.80563184 0.58483079 0.09573589]
  [0.28771221 0.33191397 0.31039118 0.14854485]
  [0.86666204 0.64463218 0.08534115 0.83605941]]]

Same shape as above array, but with a different data type:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
float64
int32


In [128]:
""" The numpy.full() function is used to create a new array of the specified shape and type, 
filled with a specified value."""

' The numpy.full() function is used to create a new array of the specified shape and type, \nfilled with a specified value.'

In [129]:
np.full(3,12)

array([12, 12, 12])

In [130]:
np.full([2,2],3)

array([[3, 3],
       [3, 3]])

In [131]:
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [132]:
np.full((3,3),55,dtype=float)

array([[55., 55., 55.],
       [55., 55., 55.],
       [55., 55., 55.]])

In [133]:
"""
The numpy.full_like() function is used to create an array 
with the same shape as an existing array and fill it with a 
specific value.
"""

'\nThe numpy.full_like() function is used to create an array \nwith the same shape as an existing array and fill it with a \nspecific value.\n'

In [148]:
a = np.arange(5)
print(np.full_like(a,3))
print(np.full_like(a,1.2))
b = a.astype(float)
print(np.full_like(b,1.2))
print(np.full_like(a,np.nan, dtype=np.double))

[3 3 3 3 3]
[1 1 1 1 1]
[1.2 1.2 1.2 1.2 1.2]
[nan nan nan nan nan]


In [149]:
a.dtype

dtype('int32')